%YAML 1.2
---

imports:
    - { resource: 'secret_parameters.yml' }
    - resource: ../package.json
      pick:
        name: app.name
        version: app.version
    - resource: ../node_modules/co-config/es.js
      pick:
        index: indices.records.index
        type: indices.records.type


parameters:
  LOG_PATH: /var/log

security:
  reverseProxy: %env(REVERSE_PROXY)%
  jwt:
    secret: %env(JWT_KEY)%
    expiresIn: 30 days # https://github.com/zeit/ms
    forbidenIds: ~
#    ip:
#      inMemory: []

nodejs:
  stackTraceLimit: 10

log:
  path: %env(HOME)%%env(LOG_PATH)%

express:
  api:
    host: %env(CONDITOR_API_HOST)%
    port: %env(CONDITOR_API_PORT)%

elastic:
  maxScrollDuration: 300s # d|h|m|s|ms|micros|nanos
  maxSize: 1000
  clients:
    main:
      hosts: %env(CONDITOR_ES_HOSTS)% # String, String[], Object[]
      apiVersion: %env(CONDITOR_ES_VERSION)%
      requestTimeout: 30000
      log: # Possible values: error, info, trace, warning, debug
        - error
