%YAML 1.2
---

imports:
    - resource: secret_parameters.yml
    - resource: ../package.json
      pick:
        name: app.name
        version: app.version
    - resource: ../node_modules/co-config/es.js
      pick:
        index: parameters.RECORD_INDEX
        type: parameters.RECORD_TYPE
    - resource: sourceIdsMap.js # Map source name to sourceId name

parameters:
  LOG_PATH: /var/log
  FORBIDDEN_JWT_IDS: ~

app:
  doExitOnUnhandledRejection: true

smokeTest:
  doRun: true

security:
  reverseProxy: %env(REVERSE_PROXY)%
  jwt:
    # Do not use "None" algortihm
    # https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/
    algorithm: HS512
    secret: %env(JWT_KEY)%
    expiresIn: 30 days # https://github.com/zeit/ms
    forbiddenIds: %env(FORBIDDEN_JWT_IDS)%
#  ip:  # list authorized ip Users
#    inMemory:
#      - ip: 127.0.0.1
#        email: user@conditor.fr


nodejs:
  stackTraceLimit: 10

log:
  path: %env(HOME)%%env(LOG_PATH)%

express:
  api:
    host: %env(CONDITOR_API_HOST)%
    port: %env(CONDITOR_API_PORT)%
  allowedAccessMethods:
    - GET
    - POST
    - OPTIONS

elastic:
  maxScrollDuration: 300s # d|h|m|s|ms|micros|nanos
  maxPageSize: 1000
   # Lucene
   # https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
  queryString:
    lenient: true
    allowLeadingWildcard: false
    maxDeterminizedStates: 5000 # default:10000 protect against too-difficult queries
  clients:
    main:
      hosts: %env(CONDITOR_ES_HOSTS)% # String, String[], Object[]
      apiVersion: %env(CONDITOR_ES_VERSION)%
      requestTimeout: 30000
      log: # Possible values: error, info, trace, warning, debug
        - error
pg:
 clients:
   main:
     host: %env(PG_HOST)% # defaults to localhost
     port: %env(PG_PORT)% # defaults to 5432
     username: %env(PG_USERNAME)%
     password: %env(PG_PASSWORD)%
     database: %env(PG_DATABASE)%
     operatorsAliases: false

aggregation:
  bucket:
    terms:
      invalidFields:
        - idConditor
      maxSize: 1000

indices:
  records:
    index: %env(RECORD_INDEX)%
    type: %env(RECORD_TYPE)%
    excludes:
      - path
